src/Personas.Web/Models/ErrorViewModel.cs
using System;

namespace Personas.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Personas.Web/Models/ViewModels/Personas/PersonaVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentValidation;

namespace Personas.Web.Models.ViewModels.Personas
{
    public class PersonaVM
    {
        public int? Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Edad { get; set; }

    }

    public class PersonaVMValidation : AbstractValidator<PersonaVM>
    {
        public PersonaVMValidation() {
            RuleFor(x => x.Nombre).NotEmpty().NotNull().WithMessage("El campo Nombre es debe ser ingresado");
            RuleFor(x => x.Apellido).NotEmpty().NotNull().WithMessage("El campo Apellido es debe ser ingresado");
            RuleFor(x => x.Edad).Must(x => x <= 120).NotEmpty().WithMessage("El dato ingresado no es valido.");
        }
    }

}

src/Personas.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Personas.Web.Models;
using Personas.Web.Models.ViewModels.Personas;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Personas.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpPost]
        public IActionResult Pepe([FromBody] PersonaVM personaVM) 
        {
            return Ok();
        }
    }
}

src/Personas.Web/Controllers/PersonasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Personas.negocio.DTOs;
using Personas.negocio.Interfaces;
using Personas.Web.Models.ViewModels.Personas;
using System.Collections.Generic;
using System.Linq;

namespace Personas.Web.Controllers
{
    public class PersonasController: Controller
    {
        private readonly IPersonaServicio _personaServicio;
        private readonly IMapper _mapper;

        public PersonasController(IPersonaServicio personaServicio, IMapper mapper) 
        {
            this._personaServicio = personaServicio;
            this._mapper = mapper;
        }

        public ActionResult Index() 
        {
            List<PersonaDTO> personas = this._personaServicio.ObtenerPersonas();

            List<PersonaVM> personasVM = personas.Select(x => this._mapper.Map<PersonaDTO,PersonaVM>(x)).ToList();

            return View(personasVM);
        }

        public ActionResult Crear() {
            return View();
        }

        [HttpPost]
        public ActionResult Crear([FromForm] PersonaVM personaVM) 
        {
            if (ModelState.IsValid) 
            {
                //crear
                return Redirect("index");
            }

            return View();
        }



        public ActionResult Detalles([FromRoute] int Id) 
        {
            PersonaDTO persona = this._personaServicio.ObtenerPersonaPorId(Id);

            PersonaVM personasVM =  this._mapper.Map<PersonaDTO, PersonaVM>(persona);

            return View(personasVM);
        }
        public ActionResult Buscar([FromQuery] string p_query) 
        {
            var personas = this._personaServicio.ObtenerPersonas();

            List<PersonaVM> personasVM;

            if (!string.IsNullOrEmpty(p_query))
            {
                personasVM = personas.Select(x => this._mapper.Map<PersonaDTO, PersonaVM>(x))
                    .Where(x => x.Nombre.Contains(p_query) || x.Apellido.Contains(p_query) || x.Edad.ToString().Contains(p_query))
                    .ToList();
                return View("index", personasVM);
            }
            else {
                personasVM = personas.Select(x => this._mapper.Map<PersonaDTO, PersonaVM>(x)).ToList();
                return View("index", personasVM);
            }
        }
    }
}

src/Personas.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Personas.Web/Views/Personas/Crear.cshtml
@using Personas.Web.Models.ViewModels.Personas;
@model PersonaVM


<h3>Agregar Persona</h3>
<div>
    <form asp-action="crear" asp-controller="personas" method="post">
        <label asp-for="Nombre"></label>
        <input class="form-control-sm" asp-for="Nombre" />
        <span asp-validation-for="Nombre" class="text-danger" ></span>
        <br />
        <label asp-for="Apellido"></label>
        <input class="form-control-sm" asp-for="Apellido" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
        <br />
        <label asp-for="Edad"></label>
        <input class="form-control-sm" asp-for="Edad" />
        <span asp-validation-for="Edad" class="text-danger"></span>
        <br />
        <input class="btn-success form-control-sm" type="submit" value="Agregar"/>
        <input class="btn-danger form-control-sm" type="submit" value="Cancelar" asp-action="index" asp-controller="personas"/>
    </form>
</div>

src/Personas.Web/Views/Personas/Detalles.cshtml
@using Personas.Web.Models.ViewModels.Personas
@model PersonaVM

<h1>Personas > Detalles</h1>
<div>
    <b><label asp-for="Nombre" class="control-label"></label>:</b>
    <span>@Model.Nombre</span>
    <br />
    <b><label asp-for="Apellido" class="control-label"></label>:</b>
    <span>@Model.Apellido</span>
    <br />
    <b><label asp-for="Edad" class="control-label"></label>:</b>
    <span>@Model.Edad</span>


    <hr />
    <a asp-action="index" asp-controller="personas" class="btn btn-dark form-control-sm ">Volver</a>
</div>

src/Personas.Web/Views/Personas/Index.cshtml
@using Personas.Web.Models.ViewModels.Personas
@model List<PersonaVM>


<div class="container-fluid">
    <div class="container-fluid">
        <div class="row justify-content-between">
            <div class="col-lg-7 col-md-7 col-sm-12">
                <ul class="nav ">
                    <li class="nav-item ">
                        <a class="nav-link  btn-success" asp-area="" asp-controller="personas" asp-action="crear" ><i class="fa fa-plus" aria-hidden="true"></i>Agregar</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-12 d-lg-inline-flex d-md-inline-flex justify-content-end ">
                <form class="form-inline" asp-action="buscar" asp-controller="personas" method="get">
                    @* name=[nameParameter from method] --> Personas/buscar?p_query= [valueInput]   *@
                    <input class="form-control form-control-sm" placeholder="Buscar..." name="p_query">
                    <button class="form-control form-control-sm btn btn-info " type="submit"><i class="fa fa-search" aria-hidden="true"></i>Buscar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <h6 class="m-2">Registros: </h6>
        <div class="container-fluid overflow-auto " style="max-height:300px;">
            <table class="table table-light table-hover  border-dark table-sm small">
                <thead class=" thead-dark">
                    <tr>
                        <th>Acciones</th>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Edad</th>
                    </tr>
                </thead>
                <tbody class="table-bordered">
                    @{
                        if (Model != null)
                        {
                            int contRegistros = 1;
                            foreach (var item in Model)
                            {
                                <tr>
                                    <th>
                                        <a asp-action="eliminar" asp-controller="personas" asp-route-id=@item.Id class="text-decoration-none text-danger"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></a>
                                        <a asp-action="detalles" asp-controller="personas" asp-route-id=@item.Id class="text-decoration-none text-dark"><i class="fa fa-info fa-2x" aria-hidden="true"></i></a>
                                    </th>
                                    <th>@contRegistros</th>
                                    <td>@item.Nombre</td>
                                    <td>@item.Apellido</td>
                                    <td>@item.Edad</td>
                                </tr>

                                contRegistros = contRegistros + 1;
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Personas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Personas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Personas.Web</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Personas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>